#!/usr/bin/env ruby
$LOAD_PATH << "lib"

require 'display_cal'

if ARGV.size == 2
  if !(ARGV[0] =~ /^[-+]?[0-9]+$/) || (ARGV[0].to_i < 1 || ARGV[0].to_i > 12)
    puts "cal: #{ARGV[0]} is not a valid month number (1..12)"
  elsif !!(ARGV[1] =~ /^[-+]?[0-9]+$/) && (ARGV[1].to_i < 1 || ARGV[1].to_i > 9999)
    puts "cal: year '#{ARGV[1]}' not in range 1..9999"
  elsif ARGV[1].index(/^\d{1,4}$/) == 0
    print_month_cal(ARGV[0], ARGV[1])
  else
    puts "cal: not a valid year #{ARGV[1]}"
  end
elsif ARGV.size == 1
  if !!(ARGV[0] =~ /^[-+]?[0-9]+$/) && (ARGV[0].to_i < 1 || ARGV[0].to_i > 9999)
    puts "cal: year '#{ARGV[0]}' is not in range 1..9999"
  elsif ARGV[0].index(/^\d{1,4}$/) == 0
    print_year_cal(ARGV[0])
  else
    puts "cal: not a valid year #{ARGV[0]}"
  end
else
  puts "cal: please include arguments as positive integers either 'month year' or 'year'"
end
